version: '3.8'

services:

  # Devops Tools
  devops_tools:
    container_name: devops_tools
    image: teamdigitale/devops-tools
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DPT_BOGUS_PATH=~/dpt-bogus
    restart: unless-stopped
    tty: true
    volumes:
      - .:/devops:cached,rw
      - ${HOME}/.kube:/root/.kube:rw
      - ${HOME}/.azure:/root/.azure:rw
      - ${HOME}/.local/bin:/root/.local/bin:rw
      - ${HOME}/.gnupg:/root/.gnupg:rw
      - ${DPT_BOGUS_PATH}:/root/.password-store:rw
